const menu = [
  {
    id: 1,
    title: "Traditional Biryani ",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: ` A savory chicken and rice dish that includes layers of chicken, rice, and aromatics that are steamed together. `,
  },
  {
    id: 2,
    title: " Butter Chicken",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `A dish which is a type of curry made from chicken with a spiced tomato and butter (makhan) sauce`,
  },
  {
    id: 3,
    title: " Falooda milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `A cold dessert made with noodles.`,
  },
  {
    id: 4,
    title: "Haleem ",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: ` A stew composed of meat, lentils, and pounded wheat made into a thick paste `,
  },
  {
    id: 5,
    title: "Chicken Tikka",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `boneless chicken pieces are marinated with yogurt and spice and then grilled to perfection `,
  },
  {
    id: 6,
    title: "Samosas",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "Chicken Karahi",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `A moderately spiced curry with spice levels similar to tikka masala `,
  },
  {
    id: 8,
    title: "Sag",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `A leaf vegetable dish eaten with bread  `,
  },
  {
    id: 9,
    title: "Lassi",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `A creamy, frothy yogurt-based drink, blended with water and various fruits or seasonings (such as salt or sugar)`,
  },
];
export default menu;
